#!/usr/bin/env bash

# ============================================
# GestoraPro - Comandos Úteis de Desenvolvimento
# ============================================

echo "🚀 GestoraPro - Comandos Disponíveis"
echo "====================================="
echo ""
echo "1. DESENVOLVIMENTO"
echo "   npm run dev              - Inicia servidor de desenvolvimento"
echo "   npm run build            - Faz build para produção"
echo "   npm run preview          - Preview da build"
echo ""
echo "2. TESTES API"
echo "   npm run test:api         - Testa conectividade da API"
echo ""
echo "3. VARIÁVEIS DE AMBIENTE"
echo "   Copiar .env.example → .env.local (opcional)"
echo "   VITE_API_BASE_URL=https://ilungi-gestora-api.fly.dev"
echo ""
echo "4. CREDENCIAIS DE TESTE"
echo "   Admin: admin@example.com / admin123"
echo "   User:  user@example.com / 123456"
echo ""
echo "5. CONSOLE DO NAVEGADOR (F12)"
echo "   import { runAPITests } from './services/apiTest.ts';"
echo "   runAPITests();"
echo ""
echo "6. VERIFICAÇÕES"
echo "   - Abrir http://localhost:5173"
echo "   - Fazer login com credenciais acima"
echo "   - Criar/Editar tarefas"
echo "   - Adicionar comentários"
echo ""
echo "7. TROUBLESHOOTING"
echo "   localStorage.clear()      - Limpar dados locais"
echo "   localStorage.getItem('gestora_api_token') - Ver token"
echo "   console.log(JSON.stringify(localStorage)) - Todos os dados"
echo ""
echo "====================================="
echo "Documentação em:"
echo "  - API_QUICK_START.md"
echo "  - API_INTEGRATION.md"
echo "  - INTEGRATION_CHANGES.md"
echo ""
